// Copyright (c) 2026 LightSeek Foundation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

#include <cstdint>
#include <optional>
#include <string>

namespace tokenspeed {

enum class CacheGroupFamily { History, State };

// The scheduler's classification of a cache group. CacheGroupConfig::Kind()
// derives it from the bridge-facing family/retention pair; scheduler logic
// reads only this kind.
enum class AttnKind { kFull, kSlidingWindow, kMambaState };

enum class CacheTransferPolicy {
    Unspecified,
    FullSuffix,
    LatestSnapshot,
};

struct CacheGroupConfig {
    enum class Retention {
        FullHistory,
        SlidingWindow,
    };

    std::string group_id;
    // Tokens covered by one block-table slot. The Python declaration shape
    // (row geometry or state checkpoint) folds to this span before crossing
    // the bridge; the scheduler never sees rows, strides or checkpoints.
    std::int32_t block_granularity{};
    // Scheduler-facing (virtual) block count including the null block: the
    // physical page count of one rank times shard_count, as the Python
    // contract's virtual_block_counts publishes it.
    std::int32_t total_pages{};
    // Scheduler-facing children per LCM block: the physical packing times
    // shard_count (the contract's virtual_packing). Each of the shard_count
    // owners holds one physical child for every shard_count virtual ones.
    std::int32_t cache_blocks_per_lcm_block{1};
    Retention retention{Retention::FullHistory};
    std::optional<std::int32_t> sliding_window_tokens{};
    // A sliding History group whose rows are regenerated by bounded replay
    // instead of being prefix-cached: it is never matched, published or
    // streamed, while retention still slides its pages out. Before a local
    // prefix hit the scheduler re-feeds the group's whole retention window
    // (the largest sliding_window_tokens over all replayable groups) and
    // never leaves a prompt's final chunk shorter than it, so every page the
    // group retains -- and PD transfers, like any sliding window's retained
    // tail -- is regenerated; the decode role re-feeds nothing. False keeps
    // the group an ordinary cached window.
    bool replayable{false};
    CacheGroupFamily family{CacheGroupFamily::History};
    CacheTransferPolicy transfer_policy{CacheTransferPolicy::Unspecified};
    // Cyclic owners of this group's virtual blocks; the pool balances new
    // children across them by request load. 1 keeps the group replicated.
    std::int32_t shard_count{1};

    // The scheduler-facing kind of this group, and the only classification
    // scheduler logic reads. A State group keeps one recurrent-state
    // checkpoint per block instead of a token history: the mamba-style group
    // (GDN linear attention, conv columns), kMambaState, whose PD destination
    // layout is a LatestSnapshot. A checkpoint summarizes everything before
    // it, so nothing in such a group ever slides out: Validate() rejects State
    // with SlidingWindow retention, and a trailing token window (SWA kv,
    // compressor tails) is a sliding History group, kSlidingWindow. Every
    // other History group is kFull. The mapping is therefore one-to-one.
    AttnKind Kind() const {
        if (family == CacheGroupFamily::State) {
            return AttnKind::kMambaState;
        }
        return retention == Retention::SlidingWindow ? AttnKind::kSlidingWindow : AttnKind::kFull;
    }

    void Validate() const;
    // Validate() without the total_pages check: every field the capacity
    // model reads, so a group can be sized before its pages exist.
    void ValidateCapacityInputs() const;
};

}  // namespace tokenspeed
