// Copyright (c) 2026 LightSeek Foundation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

#include <cstddef>
#include <cstdint>
#include <functional>
#include <optional>
#include <span>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "cache/core/block_table.h"
#include "cache/core/cache_config.h"
#include "utils.h"

namespace tokenspeed {

// Why a resumable cache boundary was retained. The declaration order is its
// monotonic promotion order.
enum class CacheBoundaryKind { kChunk, kEndpoint, kPromoted };

using CacheNamespaceId = std::uint32_t;
using ContentHash = std::string;

inline constexpr CacheNamespaceId kDefaultCacheNamespaceId = 0;

struct CacheKey {
    CacheNamespaceId namespace_id{kDefaultCacheNamespaceId};
    std::uint32_t group_id{0};
    ContentHash content_hash{};
    // Ordinal of this group's page within the enclosing prefix page (the
    // prefix_granularity-token span covered by one content hash), NOT a
    // token/byte offset inside a page.
    std::int32_t page_offset{0};

    bool operator==(const CacheKey&) const noexcept = default;
};

struct CacheKeyHash {
    std::size_t operator()(const CacheKey& key) const noexcept {
        std::size_t hash = std::hash<CacheNamespaceId>{}(key.namespace_id);
        const std::size_t group_hash = std::hash<std::uint32_t>{}(key.group_id);
        hash ^= group_hash + 0x9e3779b9U + (hash << 6U) + (hash >> 2U);
        const std::size_t content_hash = std::hash<ContentHash>{}(key.content_hash);
        hash ^= content_hash + 0x9e3779b9U + (hash << 6U) + (hash >> 2U);
        const std::size_t offset_hash = std::hash<std::int32_t>{}(key.page_offset);
        return hash ^ (offset_hash + 0x9e3779b9U + (hash << 6U) + (hash >> 2U));
    }
};

struct CacheGroupSpec {
    AttnKind kind{AttnKind::kFull};
    // Only kSlidingWindow uses this value. Mamba's one-checkpoint lookback is
    // an internal retention policy rather than a model window.
    std::int32_t sliding_window{0};
    // A kSlidingWindow group regenerated by bounded replay
    // (CacheGroupConfig::replayable): the coordinator keeps it out of prefix
    // matching and publication, and the scheduler re-feeds its sliding_window
    // before a prefix hit. False is an ordinary cached window.
    bool replayable{false};
    // Number of this group's virtual CacheBlocks per LCM block (physical
    // packing times shard_count). It affects placement only, not the
    // scheduler-wide prefix granularity.
    std::int32_t cache_blocks_per_lcm_block{1};
    // Tokens represented by one CacheBlock in this group. Required: must be
    // a positive divisor of the coordinator-wide prefix granularity.
    std::int32_t block_granularity{0};
    // Cyclic owners of the virtual blocks; must divide cache_blocks_per_lcm_block.
    std::int32_t shard_count{1};
};

// How a group's table grows in one admission. The two shapes use different
// reference frames, which is why they are two types rather than one count.
//
// DenseGrowth appends to the table's current fill: num_tokens more tokens
// beyond what the table already holds, relative to its available capacity.
struct DenseGrowth {
    std::int32_t num_tokens{0};

    bool operator==(const DenseGrowth&) const noexcept = default;
};

// SparseSuffix is absolute in token space: the table's logical length becomes
// the blocks covering extent_tokens, but only slots from first_block on are
// materialized; the slots below stay null holes, preserving absolute slot
// positions. Snapshot-state local prefill materializes its last checkpoint
// and endpoint this way; decode-side PD lands the peer's endpoint snapshot
// or retained sliding tail; a replayable group is regenerated from the
// replay window's first token.
struct SparseSuffix {
    std::int32_t extent_tokens{0};
    std::int32_t first_block{0};

    bool operator==(const SparseSuffix&) const noexcept = default;
};

using GroupExtent = std::variant<DenseGrowth, SparseSuffix>;

// Per-group capacity a request asks for in one admission: what this group
// needs beyond what its table already holds. reserve_tokens is room beyond
// the extent, held for the round after, under either growth shape. The
// request owns table.
struct GroupDemand {
    BlockTable* table{nullptr};
    GroupExtent extent{DenseGrowth{}};
    std::int32_t reserve_tokens{0};
};

// Prefix pages a request completed since the coordinator last saw it, ready to
// publish. prefix_hashes is the request's cumulative completed prefix-page
// history; the pages from first_new_prefix_page on are the new ones, and this
// struct exists only when that range is non-empty. The request owns the
// storage behind both spans.
struct CompletedPages {
    std::span<const std::string> prefix_hashes{};
    std::int32_t first_new_prefix_page{0};
    // Which kind of resumable boundary the newly completed range ends on.
    CacheBoundaryKind boundary_kind{CacheBoundaryKind::kChunk};
    // State may retain an aligned checkpoint before an unaligned endpoint.
    // Its classification must not promote the History or sliding groups.
    std::optional<CacheBoundaryKind> state_boundary_kind{};
    // Prefill streams newly published history and retained state to Host.
    // Decode leaves this false; only sliding windows keep streaming.
    bool stream_completed_to_host{false};
    // Exact prefill checkpoint provenance. Allocation and token progress are
    // not proof. An empty span disables state publication for this range.
    std::span<const std::int32_t> materialized_state_boundaries{};
};

// Per-request facts about the past that ride along with one admission:
// what the request has computed since the coordinator's previous transaction
// for it. Publication and retention consume this; capacity planning consumes
// the per-group GroupDemand. Publication happens inside the admission rather
// than at result landing because "completed" is defined in scheduled stream
// order for prefill and in landed order for decode, and the next admission is
// the first point after both; keeping it inside the transaction also makes a
// failed (and same-round retried) admission side-effect free and orders it
// before retention reclaims the slots it publishes.
struct RequestProgress {
    // Absent when no new prefix page completed since the previous admission.
    std::optional<CompletedPages> completed_pages{};
    // Tokens computed so far, driving each group's retention. Absent on a
    // request's first admission, whose tables hold nothing to reclaim.
    // Required whenever completed_pages is present.
    std::optional<std::int32_t> num_computed_tokens{};
    // The prompt endpoint identifies its last aligned history window without
    // changing publication or retention for any cache group.
    std::optional<std::int32_t> endpoint_tokens{};
};

struct PrefixMatch {
    std::vector<CacheBlockRef> blocks{};

    std::int32_t NumHitBlocks() const {
        std::int32_t count = 0;
        for (const CacheBlockRef& block_ref : blocks) {
            count += block_ref ? 1 : 0;
        }
        return count;
    }
};

// Non-owning match shape. A nonzero slot is acquired only after the coordinator
// converges every group to the final common boundary.
struct GroupPrefixProbe {
    std::vector<std::uint8_t> hits{};
};

// Pinned source/destination blocks for one asynchronous cache transfer.
struct BlockTransfer {
    std::uint32_t group_id{0};
    CacheBlockRef source;
    CacheBlockRef destination;
    CacheKey key{};
    // True when source is a freshly allocated Host block that L3 must fill
    // before the Host→Device copy.
    bool prefetch_from_storage{false};
};

}  // namespace tokenspeed
