// Copyright (c) 2026 LightSeek Foundation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#include "cache/core/cache_config.h"

#include <stdexcept>
#include <string>

namespace tokenspeed {

void CacheGroupConfig::Validate() const {
    ValidateCapacityInputs();
    if (total_pages < 1) {
        throw std::invalid_argument("Cache group '" + group_id + "': total_pages must include the null page");
    }
}

void CacheGroupConfig::ValidateCapacityInputs() const {
    if (group_id.empty()) {
        throw std::invalid_argument("CacheGroupConfig: group_id must be non-empty");
    }
    // Every remaining message names the group: a model mixes several of them,
    // and the offending one is the only actionable part of the diagnostic.
    const std::string where = "Cache group '" + group_id + "': ";
    if (block_granularity <= 0) {
        throw std::invalid_argument(where + "block_granularity must be > 0");
    }
    if (cache_blocks_per_lcm_block <= 0) {
        throw std::invalid_argument(where + "cache_blocks_per_lcm_block must be > 0");
    }
    if (shard_count <= 0 || cache_blocks_per_lcm_block % shard_count != 0) {
        throw std::invalid_argument(where + "shard_count must be positive and divide parent packing");
    }
    if (retention == Retention::SlidingWindow && (!sliding_window_tokens || *sliding_window_tokens <= 0)) {
        throw std::invalid_argument(where + "sliding_window_tokens must be > 0 for sliding groups");
    }
    if (family == CacheGroupFamily::State && retention == Retention::SlidingWindow) {
        throw std::invalid_argument(where +
                                    "a State group keeps recurrent-state checkpoints and rides FullHistory "
                                    "retention; a sliding token window is a History group");
    }
    if (replayable && (retention != Retention::SlidingWindow || family != CacheGroupFamily::History)) {
        throw std::invalid_argument(where +
                                    "only a sliding History group can be regenerated by bounded replay; a "
                                    "full-history group is prefix-closed and shared");
    }
}

}  // namespace tokenspeed
