# Copyright (c) 2026 LightSeek Foundation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""DeepSeek V4.1 checkpoint-local DSpark drafter over LCM-owned windows.

Every stage's context window is a field of the target's SWA cache group, so
the drafter holds no per-request state: rows are written at the target's SWA
slots for the very rows the target's decoder just processed -- the backend's
``decoder_view()``, each prompt's last window plus the decode rows, which is
also the layout of the captured taps -- and the block draft reads the 128
positions before its anchor through the backend's slot resolver. Prefix hits
(the SWA group is regenerated by bounded replay, these rows with it), PD
transfer and L2 therefore carry the draft state with the KV.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import torch
from tokenspeed_kernel.ops.attention import dsv41

from tokenspeed.runtime.execution.context import ForwardContext
from tokenspeed.runtime.execution.drafter.base import BaseDrafter
from tokenspeed.runtime.execution.drafter.deepseek_v4_dspark import (
    DeepseekV4DSpark,
)
from tokenspeed.runtime.execution.forward_batch_info import (
    CaptureHiddenMode,
    ForwardMode,
)
from tokenspeed.runtime.execution.output_layout import ForwardOutputLayout
from tokenspeed.runtime.layers.attention.deepseek_v41_geometry import (
    V41_SWA_GROUP_ID,
)
from tokenspeed.runtime.models.deepseek_v4_dspark_ops.heads import (
    dspark_greedy_workspace,
    sample_dspark_block_greedy,
)
from tokenspeed.runtime.utils import get_colorful_logger
from tokenspeed.runtime.utils.nvtx import nvtx_range
from tokenspeed.runtime.utils.spec_block_geometry import validate_block_widths

if TYPE_CHECKING:
    from tokenspeed.runtime.execution.input_buffer import InputBuffers
    from tokenspeed.runtime.execution.model_runner import ModelRunner
    from tokenspeed.runtime.execution.runtime_states import RuntimeStates
    from tokenspeed.runtime.layers.logits_processor import LogitsProcessorOutput


logger = get_colorful_logger(__name__)


class DeepseekV41DSpark(BaseDrafter):
    """V4.1 DSpark block drafter whose windows live in the SWA cache group."""

    shares_target_embed_head = True

    def __init__(
        self,
        spec_num_tokens: int,
        spec_num_steps: int,
        draft_model_runner: ModelRunner,
        attn_backend,
        token_to_kv_pool,
        runtime_states: RuntimeStates | None,
        input_buffers: InputBuffers,
        vocab_size: int,
    ) -> None:
        super().__init__(
            spec_num_tokens=spec_num_tokens,
            spec_num_steps=spec_num_steps,
            draft_model_runner=draft_model_runner,
            runtime_states=runtime_states,
            input_buffers=input_buffers,
            attn_backend=attn_backend,
            token_to_kv_pool=token_to_kv_pool,
            vocab_size=vocab_size,
        )
        DeepseekV4DSpark._validate_tp_only_mapping(draft_model_runner.mapping)

        self.device = torch.device(draft_model_runner.device)
        self.draft_model = draft_model_runner.model
        self.model = self.draft_model.model
        self.block_size = int(self.model.block_size)
        validate_block_widths(
            "DSPARK", self.block_size, spec_num_steps, spec_num_tokens
        )
        self.target_layer_ids = list(self.model.target_layer_ids)
        self.hidden_width = len(self.target_layer_ids) * int(self.model.hidden_size)
        max_bs = int(self.input_buffers.max_bs)
        self.next_tokens_buf = torch.empty(
            (max_bs, self.spec_num_tokens), dtype=torch.int32, device=self.device
        )
        self.draft_tokens_buf = torch.empty(
            (max_bs, self.block_size), dtype=torch.int32, device=self.device
        )
        self.start_pos_buf = torch.empty(
            (max_bs,), dtype=torch.int64, device=self.device
        )
        self.candidates, self.partials = dspark_greedy_workspace(
            int(self.draft_model.mapping.attn.tp_size),
            max_bs,
            int(self.draft_model.lm_head.num_embeddings_per_partition),
            self.device,
        )

    def idle_forward_global_num_tokens(
        self, global_num_tokens: list[int], global_bs: list[int]
    ) -> list[list[int]]:
        # Block drafter: one draft forward proposes the whole block.
        del global_bs
        return [global_num_tokens]

    def wire_target(self, target_model) -> None:
        """Bind execution resources; model setup already configured capture."""
        self.target_model = target_model
        self.lm_head = self.draft_model.lm_head
        self.tp_group = target_model.logits_processor.tp_group

    def prepare_request_state(
        self,
        request_ids: list[object],
        request_pool_indices: list[int],
        num_extends: int,
    ) -> None:
        """Window pages are scheduler-owned; nothing to refresh per round."""
        del request_ids, request_pool_indices, num_extends

    def _draft_decode_rows(
        self,
        base_ctx: ForwardContext,
        start_pos: torch.Tensor,
        next_tokens: torch.Tensor,
    ) -> None:
        num_extends = base_ctx.num_extends
        num_decodes = base_ctx.bs - num_extends
        if num_decodes <= 0:
            return
        backend = base_ctx.attn_backend
        pool = base_ctx.token_to_kv_pool
        meta = backend.query_metadata(ForwardMode.DECODE)
        width = self.spec_num_tokens
        # The anchor is the last accepted verify row; it and every earlier
        # accepted position were written above, so history ends at start_pos.
        history_slots, _ = backend.window_slots(
            V41_SWA_GROUP_ID,
            start_pos,
            meta.request_indices[: num_decodes * width : width],
        )
        bonus = next_tokens[num_extends:, 0]
        draft_ctx = ForwardContext(
            attn_backend=backend,
            token_to_kv_pool=pool,
            bs=num_decodes,
            num_extends=0,
            output_layout=ForwardOutputLayout(0, 0, num_decodes, self.block_size),
            input_num_tokens=num_decodes * self.block_size,
            forward_mode=ForwardMode.DECODE,
            capture_hidden_mode=CaptureHiddenMode.NULL,
            all_decode_or_idle=base_ctx.all_decode_or_idle,
        )
        draft_hidden = self.model.forward_backbone(
            bonus, start_pos, history_slots, pool, draft_ctx
        )
        local_logits = self.model.local_base_logits(draft_hidden, self.lm_head.weight)
        sample_dspark_block_greedy(
            local_logits,
            bonus,
            self.model.markov_head,
            self.lm_head,
            self.tp_group,
            self.candidates,
            self.partials,
            self.draft_tokens_buf[:num_decodes],
        )
        next_tokens[num_extends:, 1:].copy_(self.draft_tokens_buf[:num_decodes])

    @nvtx_range("drafter:dspark", color="purple")
    def run(
        self,
        base_ctx: ForwardContext,
        logits_output: LogitsProcessorOutput,
        output_tokens: torch.Tensor,
        accept_lengths: torch.Tensor,
    ) -> torch.Tensor:
        if not hasattr(self, "target_model"):
            raise RuntimeError("DSPARK drafter is not bound to the target model.")
        hidden_states = logits_output.hidden_states
        if hidden_states is None:
            raise RuntimeError("DSPARK requires target hidden-state captures.")
        if hidden_states.ndim != 2 or hidden_states.shape[1] != self.hidden_width:
            raise RuntimeError(
                "DSPARK target hidden-state shape mismatch: "
                f"expected [tokens, {self.hidden_width}], got "
                f"{tuple(hidden_states.shape)}."
            )
        backend = base_ctx.attn_backend
        pool = base_ctx.token_to_kv_pool
        num_extends = base_ctx.num_extends
        # The taps were captured on the decoder view: each extend request's
        # kept tail, then the decode rows (graph padding rows after them).
        view = backend.decoder_view()
        prefill_tokens = 0 if view.prefill is None else view.prefill.positions.numel()
        num_decodes = base_ctx.bs - num_extends
        decode_tokens = num_decodes * self.spec_num_tokens
        rows = prefill_tokens + decode_tokens
        if rows > hidden_states.shape[0] or rows > view.metadata.positions.numel():
            raise RuntimeError(
                "DSPARK token rows exceed captured hidden-state rows: "
                f"{rows} > {hidden_states.shape[0]}."
            )

        # Output-bearing rows get their bonus token as next-round row
        # (completing prefills keep it; decode rows overwrite the proposal
        # columns below), and each decode request's anchor is its last
        # accepted verify position. Incomplete prefills have no token, so
        # their rows in [num_prefill_outputs, num_extends) are left as is.
        next_tokens = self.next_tokens_buf[: base_ctx.bs]
        if rows == 0:
            return next_tokens

        start_pos = self.start_pos_buf[:num_decodes]
        num_prefill_outputs = base_ctx.output_layout.num_prefill_outputs
        dsv41.dspark_anchors(
            output_tokens,
            accept_lengths,
            view.metadata.positions[prefill_tokens:rows],
            num_extends,
            self.spec_num_tokens,
            next_tokens,
            start_pos,
            num_prefill_outputs=num_prefill_outputs,
        )

        # Every captured row writes its window row: a prompt's kept tail seeds
        # the history the first decode reads, verify rows refresh the block
        # just verified. Rejected rows sit past the anchor and are rewritten
        # by the step that accepts them.
        self.model.write_context_kv(
            hidden_states[:rows],
            view.metadata.positions[:rows],
            view.metadata.swa_write_slots[:rows],
            pool,
        )
        self._draft_decode_rows(base_ctx, start_pos, next_tokens)
        next_tokens[:num_prefill_outputs].clamp_(0, int(self.vocab_size) - 1)
        next_tokens[num_extends:].clamp_(0, int(self.vocab_size) - 1)
        return next_tokens

    def draft(self, *args, **kwargs) -> torch.Tensor | None:
        raise RuntimeError("DSPARK drafts through run() with target captures.")
