# Copyright (c) 2026 LightSeek Foundation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import dataclasses
import struct
from collections.abc import Mapping

from tokenspeed.runtime.pd.cache_protocol import (
    CachePDBlockManifest,
    CachePDLayerwiseBlockSelection,
    CacheProducerSchedule,
    CacheTransferContract,
)
from tokenspeed.runtime.pd.topology import PDParallelTopology
from tokenspeed.runtime.pd.transfer_plan import (
    MAX_CACHE_TP_SIZE,
    CachePageOwnerFilter,
    CacheTransferFragment,
)


def _bounded_ascii_uint(frame: bytes, *, name: str, minimum: int, maximum: int) -> int:
    max_digits = len(str(maximum))
    if (
        not isinstance(frame, bytes)
        or not 1 <= len(frame) <= max_digits
        or any(byte < ord("0") or byte > ord("9") for byte in frame)
        or len(frame) > 1
        and frame[0] == ord("0")
    ):
        raise ValueError(f"{name} must be canonical unsigned ASCII")
    value = int(frame)
    if not minimum <= value <= maximum:
        raise ValueError(f"{name} is out of range")
    return value


@dataclasses.dataclass
class KVArgs:
    engine_rank: int
    kv_data_ptr: int
    ib_device: str
    gpu_id: int
    cache_layout: CacheTransferContract
    cache_fields_by_stage: tuple[tuple[str, ...], ...]
    cache_producer_schedule: CacheProducerSchedule | None = None
    # Full-model logical contract for the PD wire when the local arena/plan
    # is narrowed to a stage window; None means cache_layout is already it.
    wire_cache_layout: CacheTransferContract | None = None

    @property
    def wire_layout(self) -> CacheTransferContract:
        return (
            self.wire_cache_layout
            if self.wire_cache_layout is not None
            else self.cache_layout
        )


class KVTransferError(Exception):
    def __init__(
        self, bootstrap_room: int, failure_reason: str, remote_endpoint: str = None
    ):
        super().__init__(failure_reason)
        self.bootstrap_room = bootstrap_room
        self.failure_reason = failure_reason
        self.remote_endpoint = remote_endpoint

    def __str__(self):
        if self.remote_endpoint:
            return f"KVTransferError(bootstrap_room={self.bootstrap_room}, remote_endpoint={self.remote_endpoint}): {self.failure_reason}"
        else:
            return f"KVTransferError(bootstrap_room={self.bootstrap_room}): {self.failure_reason}"


# prefill
@dataclasses.dataclass
class TransferKVChunk:
    room: int
    is_last: bool
    # First token generated by prefill (delivered via ZMQ, not RDMA). -1 = unavailable.
    bootstrap_token: int = -1
    begin_cache_step: int | None = None
    layerwise_interval: int = 1
    wait_for_bootstrap_token: bool = False
    spec_candidate_ids: list[int] | None = None
    block_manifest: CachePDBlockManifest | None = None
    # Process-local group-aware block window for CachePD layerwise transfer.
    # Decode continues to publish one immutable full request manifest.
    cache_block_selection: CachePDLayerwiseBlockSelection | None = None


# decode
@dataclasses.dataclass
class TransferInfo:
    """One request manifest associated with a registered Decode session."""

    room: int
    mooncake_session_id: str
    block_manifest: CachePDBlockManifest | None = None

    @property
    def is_dummy(self) -> bool:
        return self.block_manifest is None

    @staticmethod
    def route_header_from_zmq(msg: list[bytes]) -> tuple[int, str]:
        if not isinstance(msg, list) or len(msg) != 3:
            raise ValueError("CachePD pre-allocation requires exactly 3 frames")
        room = _bounded_ascii_uint(
            msg[0], name="CachePD room", minimum=0, maximum=(1 << 63) - 1
        )
        session_id = msg[1].decode("ascii")
        if not session_id or len(session_id) > 512:
            raise ValueError("CachePD request requires a Decode session")
        return room, session_id

    @classmethod
    def from_zmq(cls, msg: list[bytes]):
        room, session_id = cls.route_header_from_zmq(msg)
        block_manifest = (
            CachePDBlockManifest.from_wire_bytes(msg[2]) if msg[2] else None
        )
        return cls(
            room=room,
            mooncake_session_id=session_id,
            block_manifest=block_manifest,
        )


# decode
@dataclasses.dataclass(frozen=True)
class KVArgsRegisterInfo:
    endpoint: str
    dst_port: int
    mooncake_session_id: str
    dst_kv_ptr: int
    peer_cache_layout: CacheTransferContract
    decode_tp_size: int
    decode_tp_rank: int
    # Computed once by the receiving Prefill rank from the typed registration.
    transfer_fragments: tuple[CacheTransferFragment, ...] = ()
    # The route's decision for every DCP-sharded group: the blocks this
    # Prefill rank owns and sends, or None for a group its route carries no
    # fragment of. None as a whole until the route has been planned.
    transfer_owner_filters: Mapping[str, CachePageOwnerFilter | None] | None = None
    is_dummy: bool = False
    expected_decode_ranks: frozenset[int] = frozenset()

    @staticmethod
    def route_header_from_zmq(msg: list[bytes]) -> tuple[str, int, str]:
        """Parse the reply route even when the typed layout is later rejected."""
        if len(msg) != 8 or msg[0] != b"None":
            raise ValueError("CachePD slab registration requires exactly 8 frames")
        endpoint = msg[1].decode("ascii")
        session_id = msg[3].decode("ascii")
        if not endpoint or len(endpoint) > 255:
            raise ValueError("CachePD registration endpoint is invalid")
        if not session_id or len(session_id) > 512:
            raise ValueError("CachePD registration session is invalid")
        dst_port = _bounded_ascii_uint(
            msg[2], name="CachePD registration port", minimum=1, maximum=65535
        )
        return endpoint, dst_port, session_id

    @classmethod
    def from_zmq(cls, msg: list[bytes]):
        endpoint, dst_port, session_id = cls.route_header_from_zmq(msg)
        if len(msg[4]) != 8:
            raise ValueError("CachePD slab pointer frame must be exactly 8 bytes")
        peer_cache_layout = CacheTransferContract.from_wire_bytes(msg[5])
        decode_tp_size = _bounded_ascii_uint(
            msg[6],
            name="CachePD decode_tp_size",
            minimum=1,
            maximum=MAX_CACHE_TP_SIZE,
        )
        decode_tp_rank = _bounded_ascii_uint(
            msg[7],
            name="CachePD decode_tp_rank",
            minimum=0,
            maximum=decode_tp_size - 1,
        )
        dst_kv_ptr = struct.unpack("Q", msg[4])[0]
        if dst_kv_ptr == 0:
            raise ValueError("CachePD slab pointer must be nonzero")
        return cls(
            endpoint=endpoint,
            dst_port=dst_port,
            mooncake_session_id=session_id,
            dst_kv_ptr=dst_kv_ptr,
            peer_cache_layout=peer_cache_layout,
            decode_tp_size=decode_tp_size,
            decode_tp_rank=decode_tp_rank,
        )


@dataclasses.dataclass
class KVManagerArgs:
    bootstrap_port: int
    dist_init_addr: str

    topology: PDParallelTopology

    enable_metrics: bool
    enable_dp_attention: bool

    served_model_name: str
    app_key: str
    metrics_reporters: str
